### ISSUE TITLE
Change curl URLs to https:// in the templates.

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-edtf#12]

**Comment by ldko** [comment]
I don't know if we should hard code https. It could be a setting or left as-is for now considering on dev/local instances, we will likely not be using https whereas in production http will redirect to https--err if we include the `-L` flag with the `curl` command.

**Comment by madhuBayy** [comment]
This has been addressed in [#16](https://github.com/unt-libraries/django-edtf/pull/16)
