### ISSUE TITLE
Can I use this as a django field type? 

### ISSUE THREAD

**Issue by intrepidocabral** [unt-libraries/django-edtf#6]
How can I deal with EDTF in django models and django admin forms by extension?

**Comment by vphill** [comment]
Hey there, 

I don't think django-edtf  will work for that purpose.  This is just a validation service that provides a web service to say if a given date string is an EDTF valid sting.  If that makes sense. 

The full app can be seen here - http://digital2.library.unt.edu/edtf/

It doesn't allow for any direct integration into django models.

**Comment by intrepidocabral** [comment]
Hi @vphill !

Thanks for answer here. So, ok! I got it. My question was a attempt quit doubts about the django-edft goals. I will close issue, ok? 

Best for you! 

note: there is a project called python edft wich claims an possible django edft implementation. I tryed that, but did not get a very good result. https://github.com/ixc/python-edtf
